#markdown: rdiscount
#pygments: true
markdown: kramdown
highlighter: true
permalink: /:year/:month/:day/:title.html
name: "Min's code drawer"

kramdown:
    input: GFM

author: "mamin506"
#disqus: ""  # register a disqus account if need

navigations:
    - title: Archive
      class: fa fa-list-ul
      href: /archive.html
    - title: Tags
      class: fa fa-tags
      href: /tags.html
    - title: About
      class: fa fa-user
      href: /about.html
    #- title: Gallery
    #  class: fa fa-film
    #  href: http://foto.lhzhang.com
    #- title: Blogroll
    #  class: fa fa-link
    #  href: /links.html
    - title: Subscribe
      class: fa fa-rss
      href: /atom.xml
